stages:
  - validate
  - plan
  - apply
  - build_frontend
  - deploy_frontend
#  - deploy_backend

validate_terraform:
  image:
    name: hashicorp/terraform:1.5.6
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: validate
  script:
    - cd terraform
    - terraform init
    - terraform validate

plan_terraform:
  image:
    name: hashicorp/terraform:1.5.6
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: plan
  script:
    - cd terraform
    - terraform init
    - terraform plan

apply_terraform:
  image:
    name: hashicorp/terraform:1.5.6
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: apply
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve

build_frontend:
  image: node:21.7.0
  stage: build_frontend
  script:
    - cd calendify-frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - calendify-frontend/build
  only:
    refs:
      - main
#    changes:
#      - calendify-frontend/**

deploy_frontend:
  image: python:3.9-alpine
  stage: deploy_frontend
  environment:
    name: production
  dependencies:
    - build_frontend
  before_script:
    - apk add --no-cache python3 py3-pip
    - pip install awscli
  script:
    - aws s3api list-buckets
    - aws s3 sync calendify-frontend/build/ s3://$S3_NAME --delete --region $REGION
  only:
    refs:
      - main
#    changes:
#      - calendify-frontend/**

#deploy_backend:
#  image: docker:latest
#  stage: deploy_backend
#  services:
#    - docker:dind
#  script:
#    - cd backend
#    - docker build -t your-ecr-repo-url:latest .
#    - docker login -u AWS -p $(aws ecr get-login-password --region your-region) your-ecr-repo-url
#    - docker push your-ecr-repo-url:latest
#    - aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
#  only:
#    changes:
#      - backend/**
